DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	id VARCHAR(31) PRIMARY KEY,
	discordId VARCHAR(31),
	accessToken VARCHAR(255) NOT NULL,
	expirationDate VARCHAR(31) NOT NULL,
	refreshToken VARCHAR(255),
	etag VARCHAR(63),
	lastAdded VARCHAR(31) DEFAULT CURRENT_TIMESTAMP
);