name = "spotify-saved-tracks-webhook"
main = "./src/index.ts"
compatibility_date = "2025-02-01"
routes = [
  { pattern = "spotify.trombett.org", custom_domain = true }
]
workers_dev = false
upload_source_maps = true

[observability]
enabled = true

[placement]
mode = "smart"

[triggers]
crons = [ "* * * * *" ]

[vars]
REDIRECT_URI = "https://spotify.trombett.org/callback"

[[d1_databases]]
binding = "DB"
database_name = "SPOTIFY_WEBHOOK"
database_id = "8b50f82c-bf39-4cb2-a0e9-dd12d6da11b4"
